spring.application.name=PIE

server.port=8080
server.address=0.0.0.0
server.ssl.enabled=false

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.hbm2ddl.auto=update
spring.jpa.properties.hibernate.event.merge.entity_copy_observer=allow

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/helpdesk?useUnicode=true&serverTimezone=UTC
spring.datasource.username=
spring.datasource.password=

jwt.expirationTime=28800000
jwt.secret=in38v3hniHUi7Gu6vbiuJSAU6gHAo

spring.datasource.tomcat.testOnBorrow=true
spring.datasource.tomcat.validationQuery=SELECT 1
spring.datasource.hikari.maxLifeTime=300000